### ISSUE TITLE
Can't take items out and when putting items in their name is nil (property inventory)

### ISSUE THREAD

**Issue by Rhydium** [esx-framework/esx_property#117]
This is a weird issue, because I can take some stuff out when the server just restarted, but stuff gets weird when I try to put stuff in. I am able to put items in to the house inventory but it says 'You have stored 1x nil'. And then when I try to take stuff out of my house inventory it doesn't even open up the menu with all the items but I get this error:
`SCRIPT ERROR: @esx_property/client/main.lua:533: attempt to concatenate a nil value (field 'label')`

I can't find anything about this anywhere, so my best hope is someone here sees it and is able to help me out!

**Comment by BERENGENITA** [comment]
Anyone solved this yet?

**Comment by j5coat** [comment]
also looking for a fix for this, everything is stored in the database still. The same problem, the item is nil when putting it in and the menu never comes up to remove items.

**Comment by Fabiorochapt** [comment]
Go to client.lua line 534 and change value = item.label to value=item.name

`if item.count > 0 then
				table.insert(elements, {
					label = item.name .. ' x' .. item.count,
					type = 'item_standard',
					value = item.name
				})
			end
		end`

**Comment by fransdg** [comment]
> 
> 
> Go to client.lua line 534 and change value = item.label to value=item.name
> 
> `if item.count > 0 then table.insert(elements, { label = item.name .. ' x' .. item.count, type = 'item_standard', value = item.name }) end end`

did not work for me...

**Comment by Rhydium** [comment]
Closing this issue as it's been open for a long time and I don't think it will be fixed.
