### ISSUE TITLE
SCRIPT ERROR: @esx_property/server/main.lua:69: attempt to get length of a nil value (local 'properties')

### ISSUE THREAD

**Issue by gritzgbp** [esx-framework/esx_property#137]
cannot seem to figure out the issue, properties table is in mysql database too
![b577a7687f1189d4c22f053f7048afaa](https://user-images.githubusercontent.com/80194578/110234207-13eed680-7f21-11eb-9168-3884cf5f37f0.png) 
![98bd27d3488b4b72502ed1a3f018dd44](https://user-images.githubusercontent.com/80194578/110234223-29640080-7f21-11eb-80b6-41f63e78daca.png)

**Comment by weller197** [comment]
i have the same problem, if you sort it out please let me know how, been stuck on this for 3 days now and still cant figure out the problem

**Comment by gritzgbp** [comment]
> i have the same problem, if you sort it out please let me know how, been stuck on this for 3 days now and still cant figure out the problem

yes, fixed it by changing 'use es_extended' in the property sql queries to use whatever you're database is that your server is using
