### ISSUE TITLE
attempt to index a nil value (global 'ESX') & unexpected symbol near '<\226>'

### ISSUE THREAD

**Issue by jeboysisi** [esx-framework/esx_property#21]
I am getting the following error causing esx_property to not work at all.

![afbeelding](https://github.com/esx-framework/esx_property/assets/127330857/b561ca6f-789e-41ac-af5a-73befcf73743)

The code is not changed and is exactly how it came from github

**Comment by TheFantomas** [comment]
Hi @jeboysisi!

Me and @Thekuca tried to reproduce this "bug", unfortunately without success... 

We use the latest ESX, i.e. 1.10.1 :D And of course the source code of esx_property. Try to really update to the latest version. If the bug still appears, we will ask for some better info.

From my point of view, that's all.

Best regards and have a nice day
@TheFantomas

**Comment by jeboysisi** [comment]
@TheFantomas 
I am currently making a new server from scratch in 1.9.4.
I havent tried adding esx property yet.
I have been looking online for a while but can't find how to update esx while keeping all other stuff.
Do you know how to or where to find the way to update it?
I will let you know how it goes on 1.9.4, my previous server (where the error happend) was older than 1.6.
Thanks

**Comment by jeboysisi** [comment]
It works fine using 1.9.4
I only noticed that when I click replace storage and try to open the existing storage I get stuck in the menu and can't do anything anymore. I did it because I miss clicked, I wasn't suposed to click replace storage so I thought I was editing interior.
