### ISSUE TITLE
Problem with property

### ISSUE THREAD

**Issue by pep021** [esx-framework/esx_property#25]
Hello i have a problem. Since the new mod menu versions came out people keep deleting my properties because the owned properties are in the server folder. Is there any way i could move the property thing to the database so the modders cant keep deleting my players houses ?

**Comment by Gellipapa** [comment]
@pep021 Hi! There is no way to do it at the moment, there was an attempt to rewrite the property but unfortunately it is almost impossible to write it in a way that works without any changes and is optimized. Maybe we will write property 2.0 in the near future but I can't say in advance.
