### ISSUE TITLE
Can't take the weapon out

### ISSUE THREAD

**Issue by s002222588** [esx-framework/esx_property#86]
In my server, people can deposit the weapon in their property
but when they take it out, it comes a script error like this:

SCRIPT ERROR: @esx_property/server/main.lua:251: attempt to index a nil value (global 'data')
> handler (@esx_datastore/server/main.lua:72)
> handler (@esx_property/server/main.lua:249)

and then nothing happen, the weapon still in the property inventory

This is my server/main.lua line 249-261

		TriggerEvent('esx_datastore:getDataStore', 'property', xPlayerOwner.identifier, function(store)
			local storeWeapons = store.get('weapons') or {}
			local weapon = storeWeapons[data.current.count] -- count is the index

			if weapon then
				if not xPlayer.hasWeapon(weaponName) then
					table.remove(storeWeapons, data.current.count)
					store.set('weapons', storeWeapons)

					xPlayer.addWeapon(weapon.name, weapon.ammo)
				end
			end
		end)

Any solution to solve this problem?

**Comment by BlackZon77** [comment]
i have that problem too

**Comment by LeagueTM** [comment]
Same.

**Comment by GetParanoid** [comment]
Also having the same issue

**Comment by Bultozas** [comment]
I fixed it by putting this lines
start from 248

	elseif type == 'item_weapon' then
		TriggerEvent('esx_datastore:getDataStore', 'property', xPlayerOwner.identifier, function(store)
			local storeWeapons = store.get('weapons') or {}
			local weaponName   = nil
			local ammo         = nil


			for i=1, #storeWeapons, 1 do
				if storeWeapons[i].name == item then
					weaponName = storeWeapons[i].name
					ammo       = storeWeapons[i].ammo

					table.remove(storeWeapons, i)
					break
				end
			end

			store.set('weapons', storeWeapons)
			xPlayer.addWeapon(weaponName, ammo)
		end)
	end
end)

enjoy!!!
sorry for my bad english :)

**Comment by strianodev** [comment]
> I fixed it by putting this lines
> start from 248
> 
> ```
> elseif type == 'item_weapon' then
> 	TriggerEvent('esx_datastore:getDataStore', 'property', xPlayerOwner.identifier, function(store)
> 		local storeWeapons = store.get('weapons') or {}
> 		local weaponName   = nil
> 		local ammo         = nil
> 
> 
> 		for i=1, #storeWeapons, 1 do
> 			if storeWeapons[i].name == item then
> 				weaponName = storeWeapons[i].name
> 				ammo       = storeWeapons[i].ammo
> 
> 				table.remove(storeWeapons, i)
> 				break
> 			end
> 		end
> 
> 		store.set('weapons', storeWeapons)
> 		xPlayer.addWeapon(weaponName, ammo)
> 	end)
> end
> ```
> 
> end)
> ..
> ..
> 
> enjoy!!!
> sorry for my bad english :)

You save me, thank you!!!!
